version: 1.0.{build}
image: Visual Studio 2019
configuration: Debug
clone_depth: 50
platform: x64

cache:
  - c:\tools\vcpkg\installed

install:
  - vcpkg install glm:x64-windows-static

before_build:
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -G "Visual Studio 16 2019" ..

build:
  project: build/Primordial.sln
  parallel: true
  verbosity: minimal
